name: 'Release'

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Tag release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
    - name: Semantic tag
      id: semantic_tag
      uses: paulhatch/semantic-version@v5.4.0
    - uses: oleksiyrudenko/gha-git-credentials@v2-latest
      with:
        global: true
        token: '${{ secrets.FINANZER_HA_ADDON_PAT }}'
    - name: Generate API module
      env:
       TOKEN: ${{ secrets.FINANZER_HA_ADDON_PAT }}
      run: |
        git clone https://gedemagt:$TOKEN@github.com/gedemagt/finanzer-ha-addon
        
        cd finanzer-ha-addon
        git config --global user.name "finanzer-repo"
        git config --global user.email "mail@jeshj.com"
        
        FILE=finanzer-ha-addon/config.json
        VERSION="${{steps.semantic_tag.outputs.version}}"
        cat $FILE | jq '.version = "${{steps.semantic_tag.outputs.version}}"' | tee $FILE
        
        git add $FILE
        git commit -m "Bumped version to $VERSION"
        git tag $VERSION
        git push
