name: 'Release'

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Tag release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
    - name: Semantic tag
      id: semantic_tag
      uses: paulhatch/semantic-version@v5.4.0
    - name: Generate API module
      env:
        GITHUB_TOKEN: ${{ secrets.FINANZER_HA_ADDON_PAT }}
      run: |
        git clone https://github.com/gedemagt/finanzer-ha-addon
        
        cd finanzer-ha-addon
        git config user.name "finanzer-repo"
        git config user.email "mail@jeshj.com"
        
        FILE=finanzer-ha-addon/config.json
        cat $FILE | jq '.version = "${{steps.semantic_tag.outputs.version}}"' | tee $FILE
        
        git config user.name "jeshj" 
        git config user.password "$GITHUB_TOKEN"
        
        git add $FILE
        git commit -m "Bumped version"
        echo "HELLO1"
        
        #git config --unset-all http.https://github.com/.extraheader
        echo "HELLO2"
        git push
        echo "HELLO3"
